#ifndef DISPLAY_H
#define DISPLAY_H

/* FORMAT */
#define FORMAT_BOLD       "\e[1m"
#define FORMAT_DIM        "\e[2m"
#define FORMAT_UNDERLINED "\e[4m"
#define FORMAT_RESET      "\e[0m"

/* COLORS */
#define COLOR_RED       "\e[0;31m"
#define COLOR_GREEN     "\e[0;32m"
#define COLOR_YELLOW    "\e[0;33m"
#define COLOR_BLUE      "\e[0;34m"
#define COLOR_MAGENTA   "\e[0;35m"
#define COLOR_CYAN      "\e[0;36m"
#define COLOR_L_GREY    "\e[0;37m"
#define COLOR_D_GREY    "\e[0;90m"
#define COLOR_L_RED     "\e[0;91m"
#define COLOR_L_GREEN   "\e[0;92m"
#define COLOR_L_YELLOW  "\e[0;93m"
#define COLOR_L_BLUE    "\e[0;94m"
#define COLOR_L_MAGENTA "\e[0;95m"
#define COLOR_L_CYAN    "\e[0;96m"
#define COLOR_WHITE     "\e[0;97m"
#define COLOR_BLACK     "\e[0;30m"
#define COLOR_DEFAULT   "\e[0;39m"

/* COLORS BOLD */
#define COLOR_RED_BOLD       "\e[1;31m"
#define COLOR_GREEN_BOLD     "\e[1;32m"
#define COLOR_YELLOW_BOLD    "\e[1;33m"
#define COLOR_BLUE_BOLD      "\e[1;34m"
#define COLOR_MAGENTA_BOLD   "\e[1;35m"
#define COLOR_CYAN_BOLD      "\e[1;36m"
#define COLOR_L_GREY_BOLD    "\e[1;37m"
#define COLOR_D_GREY_BOLD    "\e[1;90m"
#define COLOR_L_RED_BOLD     "\e[1;91m"
#define COLOR_L_GREEN_BOLD   "\e[1;92m"
#define COLOR_L_YELLOW_BOLD  "\e[1;93m"
#define COLOR_L_BLUE_BOLD    "\e[1;94m"
#define COLOR_L_MAGENTA_BOLD "\e[1;95m"
#define COLOR_L_CYAN_BOLD    "\e[1;96m"
#define COLOR_WHITE_BOLD     "\e[1;97m"
#define COLOR_BLACK_BOLD     "\e[1;30m"
#define COLOR_DEFAULT_BOLD   "\e[1;39m"

/* BACKGROUNDS */
#define BACKGROUND_RED       "\e[41m"
#define BACKGROUND_GREEN     "\e[42m"
#define BACKGROUND_YELLOW    "\e[43m"
#define BACKGROUND_BLUE      "\e[44m"
#define BACKGROUND_MAGENTA   "\e[45m"
#define BACKGROUND_CYAN      "\e[46m"
#define BACKGROUND_L_GREY    "\e[47m"
#define BACKGROUND_D_GREY    "\e[100m"
#define BACKGROUND_L_RED     "\e[101m"
#define BACKGROUND_L_GREEN   "\e[102m"
#define BACKGROUND_L_YELLOW  "\e[103m"
#define BACKGROUND_L_BLUE    "\e[104m"
#define BACKGROUND_L_MAGENTA "\e[105m"
#define BACKGROUND_L_CYAN    "\e[106m"
#define BACKGROUND_WHITE     "\e[107m"
#define BACKGROUND_BLACK     "\e[40m"
#define BACKGROUND_DEFAULT   "\e[49m"

#endif